### PR TITLE
fix(dispatch_messages): Rename route property to pattern

### PR DESCRIPTION
**Pull request by jrkoch**
BREAKING CHANGE: Removed Dispatch Message's Route property.
This property actually referred to Patterns and has been updated
accordingly.

### CODE REVIEW

**Comment by kennethito** [comment]
Just curious on how we manage breaking changes.  Do we communicate out to integrators? Does the server actually support either route or pattern for X amount of time?

**Comment by thzinc** [comment]
@kennethito, in this case, integrators manage it via semver and semantic-release. (Although I see we haven't tagged a version 1.0.0 yet, so we're just ticking up our minor version number at the moment.)

**Comment by jrkoch** [comment]
Whoops, will that commit message trigger a bump in major version even though we haven't hit 1.0.0 yet?

**Comment by kennethito** [comment]
@thzinc So the server will still handle the old clients?

**Comment by thzinc** [comment]
@kennethito oh, I see what you mean. No, in this case, the breaking change would break old clients, but we're reasonably sure that no one else has integrated with the dispatch messages functionality that was very recently deployed.

**Comment by kennethito** [comment]
Ah, gotcha.

**Pull request merged**
